# Generated by Django 5.1.4 on 2025-01-02 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Examen',
        ),
        migrations.RenameField(
            model_name='examenbiologique',
            old_name='laborantin_id',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='examenradiologique',
            old_name='radiologue_id',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='examenbiologique',
            name='id',
        ),
        migrations.RemoveField(
            model_name='examenradiologique',
            name='id',
        ),
        migrations.AddField(
            model_name='examenbiologique',
            name='consultation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='biologiques', to='app.consultation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examenbiologique',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examenbiologique',
            name='laborantin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='examens_biologiques', to='app.laborantin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examenbiologique',
            name='resultat',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examenradiologique',
            name='consultation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='radiologiques', to='app.consultation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examenradiologique',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examenradiologique',
            name='radiologue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='examens_radiologiques', to='app.radiologue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examenradiologique',
            name='resultat',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultation',
            name='date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='examenbiologique',
            name='examen_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='examenradiologique',
            name='examen_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
