# Generated by Django 5.1.4 on 2025-01-08 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bilanbiologique',
            old_name='cholestérol_total',
            new_name='cholesterol_total',
        ),
    ]
