# Generated by Django 5.1.4 on 2025-01-03 18:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_examen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
