# Generated by Django 5.1.4 on 2025-01-04 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_consultation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='duree',
        ),
    ]
